version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y zip
  pre_build:
    commands:
      - echo no pre_build step
  build:
    commands:
      - echo Build started on `date`
      - mkdir ./bld
      - cp ./app/*.py ./bld/
      - pip install requests -t ./bld/
      - cd ./bld
      - zip -r ../lambda_deploy.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'